project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!renv/"
  resources:
    - "assets/"
    - "_redirects"
execute:
  freeze: auto # re-render when source changes
  echo: true # show source code in output
  output: true # show results code execution
  cache: false # don't cache code junks by default
description-meta: "Jeremy R. Winget's personal website and blog"
editor:
  markdown:
    wrap: sentence
engine: knitr

website:
  title: "Jeremy R. Winget, PhD"
  site-url: "https://www.jrwinget.com"
  repo-url: https://github.com/jrwinget/website
  description: "Jeremy R. Winget's personal website and blog."
  favicon: /assets/img/logo.png
  cookie-consent: true
  search: true
  navbar:
    background: "#f2e9dc"
    logo: /assets/img/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: talks.qmd
        text: Talks
      - href: publications.qmd
        text: Publications
  page-footer:
    left: |
      {{< fa regular copyright >}} 2025 Jeremy R. Winget<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/jrwinget/website)
format:
  html:
    code-fold: false
    embed-resources: true
    self-contained: true
    theme:
      light: [flatly, assets/main.scss]
      dark: [slate, assets/main.scss]
    css: assets/styles.css
    toc: true
