---
title: "Stereotypic morality: The effects of group membership on moral foundations"
date: "2020-08-01"
date-modified: last-modified
date-format: "MMMM D, YYYY"
subtitle: "An experiment demonstrating the effects of group membership on the perception of moral foundations"
author: "J. R. Winget & R. S. Tindale"
categories: ["Research", "Psychology"]
tags: ["social-psychology", "group-dynamics", "moral-foundations", "intergroup-relations", "stereotypes", "experimental-design"]
description: "Research on how moral foundations operate from a group perspective and potential outgroup moderators of moral foundations."
publication: "Group Processes & Interpersonal Relationships, 23(5), 710-715"
---

## Abstract

Today's modern world affords many benefits, one of which is the ability to have near-instantaneous interactions with groups and cultures other than our own. Though advantageous in many situations, one challenge for these groups is navigating what they perceive to be right and wrong in a cooperative manner despite having different modes of morality. Moral foundations theory holds groups use the same moral foundations to guide their judgments and decision making, but there has been little research on how the perception of these foundations differs within and between groups. Thus, the current study examined how moral foundations operate from a group perspective and potential outgroup moderators of moral foundations. Participants rated the extent to which various groups used moral foundations in one of two conditions. Each condition contained an ingroup and three outgroups that conformed to the quadrants of the stereotype content model. Results showed significant differences in the harm, fairness, and loyalty foundations between ingroups and outgroups. Moreover, the type of outgroup significantly influenced moral foundations scores. These findings demonstrate the importance of considering moral foundations at the group level.

## Links

- [{{< fa doi >}} Publication](https://doi.org/10.1177/1368430219866502)
- [{{< fa file-pdf >}} Preprint](https://psyarxiv.com/9u835/)
- [{{< fa project-diagram >}} OSF Project](https://osf.io/84t9p/)
- [{{< fa columns >}} Conference Poster](https://osf.io/uakct/)
