---
title: Teaching Philosophy
authors: [jeremy]
date: '2021-03-26'
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
---

My overarching teaching goal is for my students to be inspired—to see the different ways of knowing about the world, primarily through the lenses of scientific discovery and psychological science. My core goals are to help students understand the concepts, theories, and perspectives that comprise psychological knowledge and inquiry, promote multiculturalism, leverage active learning strategies, and support independent, critical thinking. Throughout my academic career—from community college to research at private universities—my most inspirational instructors have been passionate about their field, dedicated to student success, and challenged students to never settle for mediocre performance. These are the same qualities I try to emphasize to inspire my students.

I strongly value the diversity of learning styles and unique perspectives—both individual and cultural—that my students bring to the classroom. Because an array of perspectives is crucial for a comprehensive evaluation, I strive to provide an environment in which students feel comfortable expressing their needs and opinions. I have found that each class offers new challenges and opportunities for my learning as an instructor. As my students change, I change. As my discipline grows, I am always motivated to meet the challenge of passing that knowledge on to my students. However, I ultimately hope to give them the curiosity and skills that will allow them to participate in the creation of that knowledge.

While I believe science is relevant to everyone's life, relevance is different for different cultures. Thus, I use a wide range of examples and analogies in class. I intentionally choose examples that are relevant to underrepresented populations and women. For example, when discussing gender effects in psychological research, I always mention that gender is not limited to two categories. This is often an excellent opportunity to discuss the continuum of human gender identification, as well as its distinction from biological sex and sexual orientation.

Racial diversity and gender balance should be encouraged in all areas of science. Greater diversity brings fresh insight into our investigation of scientific problems and demonstrates that science is inclusive rather than exclusive. As a corollary, I also believe that social justice should be a part of the science classroom. As the sociologist, Pierre Bourdieu said, "Those who have the good fortune to be able to devote their lives to the study of the social world cannot stand aside, neutral and indifferent, from the struggles in which the future of the world is at stake." I believe it is our duty as academic psychologists to discuss with our students about relevant psychological research that is related to social justice issues.

As a way of including this critical component in my research methods course, I construct a class project to examine discrimination empirically. This involves having students read the psychological literature on the effects of group membership on helping behavior. Students learned about studies demonstrating the tendency for people to help ingroup members more often than outgroup members. Still, they also read literature about potential factors that can mitigate this effect (e.g., increased empathy, decreased diffusion of responsibility). Students then conduct a research study to examine if such factors can reduce the adverse effects of group membership on helping behavior. I hope that by reviewing and conducting research on these effects, students will not only learn about the research process but also learn of empirical ways to reduce discrimination in their everyday lives.

In addition to incorporating social justice into the science classroom, I strive to integrate an equity pedagogy into all my courses. To achieve this goal, I modify my teaching in ways that attempt to facilitate the success of my students from diverse racial, cultural, and social-class groups. By having multiple methods of assessment and teaching styles, I try to create an environment in which all students have an equal chance for achievement. Therefore, I involve visual aids and hands-on activities in addition to writing papers and more formal examinations. For instance, research suggests that cooperative learning activities tend to be more beneficial for these groups compared to competitive learning activities. I am aware that to be successful, students must feel that they have an equal status in intergroup interactions, that teachers value and support cross-racial interactions, and that students from different racial groups must work together in teams to pursue common goals. As a result, I am diligent about building community within the classroom. I believe that building a community in the classroom creates a safe space in which students feel more comfortable sharing their opinions, ideas, and experiences. To achieve this, I consciously attempt to recognize and reevaluate my biases, privileges, and power to make sure I am equitable and fair. I let students know that I believe in everyone's ability.

I am also a proponent of active learning and use a variety of methods to encourage discussion and interaction on course concepts. I am very fond of creating concrete activities for abstract concepts. For example, in my research methods course, the idea of random assignment in an experimental design is very intangible. Often, students understand it is an important concept but struggle with how the process works. In the activity, I have students get into pairs and give them a fake data set of 20 participants who vary on a variety of demographic variables. Student pairs are given a coin and asked to randomly assign each one of the participants to either a control condition based on tails or an experimental condition based on heads. Students then compare the means of each demographic variable between the two groups. After doing this, the majority of students seem to have an "Ah-ha!" moment and see the two groups are now equalized in a reasonably concrete manner. Instead of only reading about the concept in the textbook, students can interact with the random assignment process to see how it works.

When I lecture, I intersperse my talk with questions that prompt students to reflect on essential points I raised during the session, share their reflections with classmates, and briefly discuss the insights gained from any class activities. I also make my slides available to all students. By distributing my lecture slides, I allow students to reflect on the central points of the class session without feeling forced to concentrate purely on note-taking.

I believe that when students engage in the writing process, they are forced to think more deeply about and engage more fully with a concept. Thus, I assign a variety of writing tasks in my courses. For instance, in my research methods course, I require students to write a formal APA-style research paper as well as a series of smaller essays, including an analysis of readings, and class observations in which the student can engage in self-reflection on the issues raised by the course and the relevance of the material to current events or their lives in general. Class observations are also useful in allowing me to engage in a private dialogue with students who may be reluctant to attend office hours but who feel comfortable in raising issues within the context of writing. Using these class observations also allows me the flexibility to pursue essential points raised by the students during a lecture without sacrificing coverage of relevant course material. Furthermore, allowing students to express themselves informally through writing affords me the opportunity for a complete assessment of a student's ability than would be possible by relying only on a combination of formal papers and examinations.

I also understand that part of a student's everyday world is the university itself. Thus, my role as a teacher includes helping students succeed in the unique culture of higher education. While I want students to be able to personalize their education via active learning, I also recognize I have expertise from which students may benefit. I believe most students will rise to the challenge when quality work is demanded of them if they are also helped to develop the skills necessary to make that possible. For this reason, I encourage critical thinking and the improvement of oral and written skills in all my classes.

I believe students are best served when they are actively and rigorously engaged in the pursuit of knowledge. An instructor may inspire, but students should be actively involved in the learning process for it to be successful. To give students greater ownership of the knowledge they encounter, I use cooperative and active learning strategies as well as lectures in my courses and try to develop assignments that foster both analytical and critical thinking and opportunities for creative application.

For example, in my statistics course, I emphasize that the ability to quantify intuitions and observations and apply tools to solve real-life problems is essential across all fields. Information about the world often is conveyed by the media in statistical terms, pointing to the need for us to have a clear understanding of the kinds of problems that statistics can and cannot be asked to solve. University students have an intuitive understanding of everyday issues, developed through their own experiences. The key to teaching statistics is to show students how to relate theoretical concepts to the knowledge of such problems they have achieved already. I facilitate the teaching of statistics by connecting statistical concepts to other courses and challenges encountered in everyday life and by using diagrams and humorous illustrations to help explain concepts.

Additionally, I emphasize the importance of the research process, rather than merely conveying a set of psychological findings. The strength of this approach is that it teaches students to think critically about research and decide for themselves if the results of a study truly support the authors' hypothesis or theory. To this end, I present key course concepts alongside a detailed description of a research study that has tested a vital aspect of that concept. Throughout this process, I ask students to generate predictions, practice interpreting data from tables and figures, discuss the implications of the findings, and identify alternative explanations for the results. This approach also permits many opportunities to highlight important concepts in research methodology, such as the use of operational definitions in the literature. I believe this approach to teaching stimulates students' intellectual curiosity, instills an appreciation for the ways psychology can be used to understand human behavior, and provides them with a toolbox for critically consuming research in any field.

In summary, I am very committed to providing an engaged learning environment that is both exciting and rigorous, one that bolsters both the student and the teacher in the pursuit of knowledge. I devise various assessment strategies that allow me to fairly assess student learning regardless of the student's background and previous experiences. Above all, I treat my students with the utmost respect, creating an environment in which students feel safe to discuss ideas and topics freely.
