---
title: "Learning while deciding in groups"
date: "2017-06-15"
date-modified: last-modified
date-format: "MMMM D, YYYY"
subtitle: "A book chapter summarizing the group decision making literature, describing when and how group decision making facilitates learning"
author: "R. S. Tindale & J. R. Winget"
categories: ["Research", "Psychology"]
tags: ["social-psychology", "group-dynamics", "decision-making", "organizational-learning", "information-processing", "book-chapter"]
description: "Review of group decision making literature with emphasis on how and when group decision making leads to learning."
publication: "The Oxford Handbook of Group and Organizational Learning"
---

## Abstract

Groups are used to make many important societal decisions. Similar to individuals, by paying attention to the information available during the decision processes and the consequences of the decisions, groups can learn from their decisions as well. In addition, group members can learn from each other by exchanging information and being exposed to different perspectives.

However, groups make decisions in many different ways and the potential and actual learning that takes place will vary as a function of the manner in which groups reach consensus. This chapter reviews the literature on group decision making with a special emphasis on how and when group decision making leads to learning.

We argue that learning is possible in virtually any group decision-making environment, but freely interacting groups create the greatest potential for learning. We also discuss when and why groups may not always take advantage of the learning potential.

## Links

- [{{< fa doi >}} Publication](https://doi.org/10.1093/oxfordhb/9780190263362.013.42)
- [{{< fa file-pdf >}} Preprint](https://psyarxiv.com/8ufgh)
